const RESPONSE_CODE = {
    SUCCESS: "200",

    HTTP_METHOD_IS_NOT_ALLOWED: "E00",
    ACCESS_TOKEN_EXPIRED: "E01",
    INVALID_BODY_PARAMETER_KEYS: "E02",
    INVALID_BODY_PARAMETER_VALUES: "E03",
    INVALID_QUERY_PARAMETER: "E04",

    USER_NOT_FOUND: "E10",
    USER_HAS_NO_MODULE_ACCESS: "E11",
    USER_PHONENUMBER_HAS_ALREADY_EXISTED: "E12",
    USER_LINE_ID_HAS_ALREADY_EXISTED: "E13",
    USER_HAS_NOT_REGISTERED_TO_THIS_MODULE: "E14", // User has no gUId
    USER_NOT_ACTIVATE: "E15", // User has no gUId
    USER_IS_THE_SAME_AS_DESTINATION: "E16",

    COMPANY_NOT_FOUND: "E20",
    LINE_LIFF_ID_NOT_FOUND: "E21",
    INVITE_LINK_EXPIRED: "E22",
    INVITE_CODE_INVALID: "E23",
    INVITE_USER_ALREADY_EXISTED: "E24",
    FAILED_TO_CREATE_TABLE: "E25",
    MISSING_COMPANY_NAME: "E26",

    MODULE_NOT_FOUND: "E30",
    MODULE_COMPANY_HAS_NO_ACCESS: "E31",
    MODULE_IS_INACTIVE: 'E32',

    // Redemption
    REDEMPTION_INSUFFICIENT_POINTS: "E40",
    REDEMPTION_CODE_INVALID: "E41",
    REDEMPTION_CODE_IS_USED: "E42",
    REDEMPTION_CODE_IS_CANCELLED: "E43",
    REDEMPTION_CODE_IS_EXPIRED: "E44",
    REDEMPTION_CODE_IS_NOT_REACH_START_DATE: "E45",
    REDEMPTION_TRANSACTION_NOT_FOUND: "E46",
    REDEMPTION_CREATING_FAIL: "E47",
    INSUFFICIENT_POINTS: "E48",

    // Store
    ORDER_NUMBER_IS_ALREADY_EXISTED: "E50",
    ORDER_AMOUNT_IS_ZERO: "E51",
    ORDER_CREATING_FAIL: "E52",
    FAILED_TO_GET_POINT_TO_BAHT_RATIO: "E53",

    // Warranty
    WARRANTY_SKU_NOT_FOUND: "E60",

    // Product
    PRODUCT_MODE_IS_MISSING: "E70",
    PRODUCT_SKU_IS_MISSING: "E71",
    PRODUCT_NOT_FOUND: "E72",
    PRODUCT_OUT_OF_STOCK: "E73",

    // Payment Gateway
    PMS_CANNOT_GET_PREFIX_COUNT: "E80",
    PMS_INTERNAL_ERROR: "E81",
    PMS_TRANSACTION_AMOUNT_IS_ZERO: "E82",
    PMS_ORDER_TYPE_NOT_FOUND: "E83",

    DYNAMODB_UPDATE_ERROR: "E90",
}

export default RESPONSE_CODE